# Generated by Django 4.2.4 on 2023-09-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refactory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_of_birth',
        ),
    ]
